xaksis/vue-good-table

- README.md
- src/components/Table.vue
Ref. Issue #14 
With the `tdClass` option in the column object, you can set your own class(es) to the cell.
With the `thClass` one, you can set classes for the th.
If provided, they will override their default classes (set by the column type).
> Custom class to cells (td)

- src/components/Table.vue
If you have many columns and want custom columns with actions you have to write all columns again?
```vue
<template slot="table-row" slot-scope="props">
<td><input type="checkbox" /></td>
// other columns start (over 20)
<td><img src="{{ props.row.imageLink }}"/></td>
<td>{{ props.row.productName }}</td>
<td>{{ props.row.productCode }}</td>
<td>{{ props.row.salePrice }}</td>
// other columns end
<td><button @click="doSomething(props.index)">show</button></td>
</template>  
```
I added two more slots for adding cols before and after the table-row. For example:
```vue
<template slot="table-row-before" slot-scope="props">
<td><input type="checkbox" /></td>
</template>
<template slot="table-row-after" slot-scope="props">
<td><button @click="doSomething(props.index)">show</button></td> …
```
> Added before and after table-row slots.

- src/components/Table.vue
Otherwise put them in the beginning (mainly for empty dates). I always got an 'Invalid Date' when my date field was empty instead of an empty date. It also had problems sorting it.
> Only parse date when it is a valid date.

- src/components/Table.vue
When `globalSearchAllowed` is set to true, the data table lose the `originalIndex` each time the filter is applied.
I create the computed property `originalRows` to avoid that problem and focus the addition of originalIndex on only one place.
> Fix mantains originalIndex when globalSearchAllowed

- dev/App.vue
- src/components/Table.vue
In the latest vue2 version, if you add the filterOptions to any column, you get a "[Vue warn]: Avoid using non-primitive value as key" warning in the console, because you have set the :key to option which is ""[object, object]" and therefore are ambiguous.
Same applies if you want to have more empty columns (with label = ''). So the key must be unique, therefore I used the index insteat of the label.
> fixed [Vue warn]: Avoid using non-primitive value as key

- src/components/types/date.js
Fixes nuxt render error:
```js
nuxt:render Rendering url /cities +0ms
{ <project path>\node_modules\date-fns\esm\index.js:3
export {default as addDays} from './addDays/index.js'
^^^^^^
SyntaxError: Unexpected token export
at createScript (vm.js:80:10)
at Object.runInThisContext (vm.js:139:10)
at Module._compile (module.js:616:28)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (<project path>\node_modules\vue-good-table\dist\vue-good-table.cjs.js:17:11)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at …
```
> Fix nuxt export error.

- src/components/VgtFilterRow.vue
What this does is skip the 400ms delay when `filterOptions: { enabled: true, trigger: 'enter' }` is set.
**Why:**
* It feels sluggish when you press enter and there is a 0.4 second delay before anything happens
* Removal of `setTimeOut` makes writing tests that involve filtering much simpler
Because the `updateFiltersOnEnter` can still be called when you are not using `trigger: 'enter'`, that means the user could type a phrase, then press enter, then 400 ms later trigger another request. So we `clearTimeout` on the `updateFiltersOnEnter` method too.
> Update Filters Immediately on enter pressed

- src/components/VgtPagination.vue
- src/components/VgtPaginationPageInfo.vue
Since I worked on a custom pagination component based on VgtPagination, I think it's possible to simplify/clean the code a little bit:
* Delete useless variables/methods
* Simplify some methods
* Add pagesCount computed property (used in isNextPossible and VgtPaginationPageInfo)
* ~~Always go to 1rst page after changing per page (to avoid issue when current page is greater than last page)~~ Fixed in https://github.com/xaksis/vue-good-table/issues/370
So I didn't add any feature (and any bug I think 🤞 ), but IMHO it will be easier to add new ones like first/last page buttons, display pages number...
> Clean VgtPagination code

- src/components/types/date.js
Hello,
There is a way to import only the needed functions from date-fns, so  i replaced those imports to get a smaller size of dependencies. #350 
original stats
```
Built in 10.59s.
┌─────────────────────────────────────────────────┐
│file                         size       gzip size│
│dist/vue-good-table.cjs.js   72.72 KB   14.45 KB │
│dist/vue-good-table.es.js    72.38 KB   14.35 KB │
│dist/vue-good-table.js       361.52 KB  70.17 KB │
│dist/vue-good-table.min.js   94.44 KB   28 KB    │
│dist/vue-good-table.min.css  12.93 KB   2.4 KB   │
│dist/vue-good-table.css      16.16 KB   2.84 KB  │
└─────────────────────────────────────────────────┘
```
new stats
```
Built in 8.65s.
┌─────────────────────────────────────────────────┐
│file                         size       gzip size│ …
```
> import only needed functions from date-fns

- package.json
The current `repository` field in `package.json` is invalid. This PR updates it to use the recommended format for GitHub.
See: https://docs.npmjs.com/files/package.json#repository
> Fix repository in package.json

- package.json
Currently, Webpack omits `vue-good-table`'s CSS files from production builds because it does not recognize them as side effects. This breaks the usage specified in the project documentation.
Read more: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
> Include CSS in Webpack production

- package.json
in my production webpack4 build the CSS for vue-good-table wasn't included in production builds (all dev builds were okay)
After some digging I've confirmed adding `*.css` to `sideEffects` in package.json fixes this issue.
Since css modifies the DOM it is counted as having side effects by webpack4 when it does its treeshaking and all that.
Can provide links to demo if you like.
> "*.css" sideEffects - fix css not included in prod build (webpack4)

- src/components/VgtTableHeader.vue
Related to issue #590, when the hidden = true property is added in a column, the getWidthStyle function receives the dom parameter as undefined for that column.
> Fix Failed to execute 'getComputedStyle' on 'Window'

- src/components/VgtTableHeader.vue
Resolves issue: #653
* Added watcher for columns change to fix issue #653 
Removed setTimeout in "setColumnStyles" to get rid of async testing issues
When testing in jest the snapshots render sometimes like:
```diff
-<th class="vgt-left-align sorting sortable">
+<th class="vgt-left-align sorting sortable" style="min-width: auto; max-width: auto; width: auto;">
```
Because of the setTimeout it would occasionally finish on-time before the snapshot fired, the fix in the tests were to fakeTimers in jest. This approach works in some cases, however it adds complexity and does not work with vue-test-utils in all scenarios.
This was initially written with setTimeout because of the fixed headers, instead this is being handled by watchers.
> BugFix: Async Column Styles

- src/components/Table.vue
- src/styles/style.scss
- vp-docs/.vuepress/config.js
- vp-docs/guide/style-configuration/sass.md
Fixes #672
This moves the V-Select styles to the component level to allow it's import to be resolved without breaking anyone's custom Sass build system.
> Fix Sass not building in last release

- src/styles/_rtl.scss
Condensed style doesn't work with RTL mode. Since the style of RTL override condensed's styles
> Fixed RTL with condensed

- src/components/Table.vue
- vp-docs/guide/advanced/grouped-table.md
This solves https://github.com/xaksis/vue-good-table/issues/715#issue-627385236
If you add data rows only to the end of your table, the latest release of vue-good-table will maintain the expanded state of all rows, and not collapse them automatically any time the data changes. But if you add a row in the middle of the table, the one that was added is automatically expanded and the one that is bumped down gets collapsed. 
**Proposed Solution**
To the `groupOptions`, add an optional `rowKey` attribute, which is used to provide a unique identifier for the row data. If provided, that key will be used to track expanded state instead of the `vgt_header_id`.
> Add rowKey option and documentation

- src/styles/_table.scss
- src/styles/style.scss
When using the `striped` class, the highlight only works on non-striped rows. 
Probably not the best way to fix this, but if the hover styling is `!important`, then it does not get overridden by the `_striped.scss` styling. I guess one should play with the selectors and their order instead, but this fix seems to work fine.
> fix: highlighting should work even when striped style is applied

- dev/App.vue
- src/components/utils/sort.js
- vp-docs/guide/configuration/column-options.md
Currently the first sort on a column sorts always in ascending order. Sometimes the user expects the first sort to sort the data in descending order. For example in a table "Most visited pages", when sorting by visits *(sessions, users ...)* one would expect the default sort order to be descending. 
With the introduced firstSortType column property this behavior can be achieved.
**Notes:**
1. This change is non-breaking
2. The docs are also updated
> Introduce new column property firstSortType

- dev/grouped-table.vue
- src/components/Table.vue
- src/components/VgtHeaderRow.vue
- vp-docs/guide/advanced/checkbox-table.md
- vp-docs/guide/advanced/grouped-table.md
Add feature to enable checking all checkboxes of a grouped table's children.
The checkbox is available in span/non-span mode in the vgt-header-row.
> Add feature to enable checking all checkboxes of a grouped table

- dev/App.vue
- package-lock.json
- package.json
- src/components/Table.vue
- src/components/VgtFilterRow.vue
- src/components/VgtTableHeader.vue
- src/index.js
- src/styles/_input.scss
- src/styles/black-rhino/black-rhino.scss
- src/styles/nocturnal/nocturnal.scss
- vp-docs/guide/advanced/README.md
- vp-docs/guide/configuration/column-filter-options.md
- vp-docs/guide/style-configuration/sass.md
Addresses issue https://github.com/xaksis/vue-good-table/issues/675
**Notes:**
* Add a slot in `VgtFilterRow`
* Create a method `updateSlotFilter` that includes the custom filter with the rest of the column filter values
* Expose the method as a prop on the slot so it can be optionally used
* Allow a `slotFilterField` to be passed in, because the property used for display may not be the same as the property for filtering
* Remove the `vue-select` code to reduce the overall bundle size.
> Remove Vue Select and Add Column Filter Slot

- src/components/VgtTableHeader.vue
- src/styles/_wrap.scss
Previously, column widths were updated only on a window resize event. This ticket makes two changes to that behavior:
1. If the page layout changes without a window resize, columns weren't getting updated. As an example, put a wrapper div around the component. Now change the width on that wrapper. The column sizes don't get updated, since the window isn't resizing.
2. If there is a fixed header, we also watch each th in the primary table header for a resize. Previously, if you were to inline table-layout: fixed onto the primary table, the fixed header wouldn't get updated, since the wrapper element didn't change sizes, just the column widths. Now column headers are watched for resize changes, and the fixed header updates accordingly if they change.
This addresses #697
> Fixed header now has a resize observer for primary column headers

- src/components/Table.vue
This is a fix I made for https://github.com/xaksis/vue-good-table/issues/560 where the top/bottom pagination widgets didn't match up.
it hooks into the changePage and perPageChanged events and ensures that either or both pagination widgets are set appropriately during these changes.
Thanks for the all the work you've put in the library, this was the only thing that was bugging me about it so I decided to fix it.
> update both sides of pagination widget during changes

- src/components/Table.vue
Currently custom column filters are only being shown when the header is not fixed (`<vue-good-table :fixed-header="false">`). This PR also adds custom column filters when the header is fixed.
> Show custom filter (column-filter) when header is fixed

- .gitignore
- dev/App.vue
- src/components/VgtFilterRow.vue
- vp-docs/guide/configuration/column-filter-options.md
Added the `column.filterOptions.styleClass` option + associated doc.
It should be easier to handle filter styling than using something like this `.vgt-table thead tr:nth-child(2)`
This addresses #459
> Fixed issue 459: StyleClass for column filters

- src/components/Table.vue
Because of the issue mentioned in https://github.com/xaksis/vue-good-table/issues/713#issuecomment-655222816 the pagination is not working properly when using grouped rows.
When including the group row in counting the rows for the pages, this error is resolved.
> fix wrong pagination on grouped rows

- src/components/Table.vue
This PR will create the functionality of disabling the checkbox selection if we pass vgtDisabled in the row object.
> [Issue: 725]: Disable row selection if a condition is met

- src/components/VgtGlobalSearch.vue
Looks like in PR #752 the search field's placeholder text was forced to null. Presumably that was a mistake. This fixes that.
> Fix search placeholder always forced to null

- src/components/Table.vue
Users can pass in `{ enabled: true }` as the sortOptions, which means `initialSortBy` would be `undefined` and `JSON.parse` throws an error when you hand it `undefined`. So we need to default the value if it is not present.
> Prevent JSON parse error

- dev/App.vue
- src/components/VgtTableHeader.vue
- vp-docs/guide/configuration/column-options.md
Add simple tooltip support for column header
> Tooltip support

- src/components/VgtTableHeader.vue
Hey,
I added a fix for situation like mine appeared during tests.
> avoid "ResizeObserver is not defined"

- src/components/Table.vue
- src/components/pagination/VgtPagination.vue
#782
Enhanced pagination options. Added support for first and last button which helps in jumping directly to first and last page. Also added support for custom text label of these buttons. Default texts are First and Last.
Support for 3 new pagination options : 
`jumpFirstOrLast : true`
`firstLabel : "1st Page"`
`lastLabel : "Last Page"`
`jumpFirstOrLast` enables support for this enhancement. This prop can take 2 values - true or false. Default value is false.
> Added support for first and last button in pagination

- src/components/pagination/VgtPaginationPageInfo.vue
#853 
`totalPage` key in the pagination information function - `infoParams()` was returning the value as undefined. `totalPage` key was incorrectly spelled as `totalPages`. Renaming it fixed this issue.
> totalPage parameter showing undefined bug fixed
