xaksis/vue-good-table

README.md
src/components/Table.vue

Allows custom filters. Solving issue #17 (apart from having to implement the fuzzy filtering yourself).

Allow custom filters

---

README.md
src/components/Table.vue

Added dropdown filter option and updated README.md

Added dropdown filter option

---

src/components/Table.vue

usage:
` <vue-good-table :columns="columns" :rows="sortedData" :paginate="true" :globalSearch="true" v-on:pageChanged="log($event)">`

Add PageChanged event and emit currentpage and total pages

---

src/components/Table.vue

Search is compatible with IE - you will need a polyfill for includes - but this is the exact same thing

changed to use search for IE compatibility

---

src/components/Table.vue

this way we can use the placeholder when using the dropdown filters

add placeholder as a filter option

---

src/components/Pagination.vue
src/components/Table.vue

This PR create the `vue-good-pagination` component to maintains pagination decoupled form `vue-good-table` and give the ability to play with it.
In the PR the user have the option to change the position of the pagination with the boolean prop `paginationOnTop` added to `vue-good-table`.

Extract paginatin to an extern component

---

src/components/Table.vue

I added and slot to have the ability to provide some HTML with actions inside the `<div class="actions">` which is empty right now.

Add slot to provide actions from outside

---

README.md

#169 slot-scope

---

README.md
src/components/Table.vue

#172 & #150 perPage event emit

---

package.json
src/components/Table.vue

This allows for searches where the data or the term itself contain accents

added diacriticless

---

README.md

This feature exists but was not documented.

Missing "allText" documentation

---

src/components/Table.vue
src/components/VgtPagination.vue

Change `vue-good-pagination` to `vgt-pagination`

Change naming of pagination to follow the same convention as others

---

src/components/Table.vue
vp-docs/guide/advanced/README.md

Add pagination-top and pagination-bottom slots to customize pagination.
https://github.com/xaksis/vue-good-table/issues/326

Custom pagination proposal

---

package.json
src/components/Table.vue

remove some lodash functions

---

package.json
src/components/Table.vue

Reverts xaksis/vue-good-table#430

Revert "remove some lodash functions"

---

package-lock.json
vp-docs/guide/advanced/grouped-table.md

Updated grouped-table documentation to match what is shown in the code blocks.

Documentation fix, #490

---

package-lock.json
package.json
src/components/Table.vue

Preliminary fix for checkbox issues in selection mode, detailed in #498. Issues appear to be related to the event.preventdefault directive attached to the selection method. Removing this directive appears to have solved the issue, pending further testing/observance of side-effects.
If the directive is indeed absolutely necessary, and setTimeout workaround exists, detailed by Evan You (here)[https://github.com/vuejs/vue/issues/5650].

Preliminary fix for checkbox issues in selection mode

---

vp-docs/guide/README.md

Solves #597 
Let me know if you need any changes.
Thanks,
Tom

[docs] - add nuxt.js documentation

---

src/components/Table.vue

***WHY***
- Sometimes we need to format the data in a column through other data in the rows.
***HOW***
- I have added the row data as the second parameter of the formatFn function.

Created new param(row) in formatFn function.

---

dev/App.vue
src/components/Table.vue
src/components/types/default.js

Related to https://github.com/xaksis/vue-good-table/issues/509

Use exact match while using filter dropdown item

---

src/components/Table.vue

Hello @xaksis I think you left a debug print in your code 😃.

Remove debug console log

---

src/components/Table.vue

removed unnecessary console.log from Table.vue

removed console.log

---

src/components/Table.vue

I believe that this addresses [issue 841](https://github.com/xaksis/vue-good-table/issues/841) that I made.

Grouped Table Not Rendering Empty Children (issue fix)
